// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

// Error defines model for error.
type Error struct {
	ErrorDetails string `json:"errorDetails"`
}

// IpLocation defines model for ipLocation.
type IpLocation struct {
	City        string  `json:"city"`
	Country     string  `json:"country"`
	CountryCode string  `json:"country_code"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

// GetV1IplocaionParams defines parameters for GetV1Iplocaion.
type GetV1IplocaionParams struct {
	// IP-address to locate.
	Ip string `json:"ip"`
}
